version: '3.7'
services:

  email-sender:
    image: devatherock/email-sender:latest
    container_name: email-sender-intg-embedded
    network_mode: "host"
    environment:
      EMAILSENDER_SMTP_EMBEDDED_ENABLED: 'true'
      EMAILSENDER_SMTP_EMBEDDED_HOST: devatherock.github.io

  health:
    image: alpine:3.20.3
    network_mode: "host"
    depends_on:
      - email-sender
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/actuator/health"]
      interval: 2s
      timeout: 60s
      retries: 30
    command: |
      sh -c '
        wget -q -O - http://localhost:8080/actuator/health
        sleep 120
      '
