version: '3.7'
services:

  email-sender:
    image: devatherock/email-sender:latest
    network_mode: "host"
    environment:
      EMAILSENDER_SMTP_EMBEDDED_ENABLED: 'true'
      EMAILSENDER_SMTP_EMBEDDED_HOST: devatherock.github.io
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 2s
      timeout: 60s
      retries: 30
