server:
  port: ${PORT:8080}
  compression:
    enabled: true
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
management:
  endpoints:
    web:
      exposure.include:
        - metrics
        - health
        - info
emailsender:
  smtp:
    embedded: false
