slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.4.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

orbs:
  gradle: circleci/gradle@2.2.0
  heroku: circleci/heroku@1.0.1

work_directory: &work_directory
  working_directory: ~/email-sender

resource_class: &resource_class
  resource_class: small
  
executors:
  jdk-executor:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory  

version: 2.1
jobs:
  publish:
    executor: heroku/default
    <<: *resource_class  
    <<: *work_directory
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker
      - attach_workspace:
          at: ~/email-sender
      - run:
          name: Build and push the docker image to registry.heroku.com
          command: |
            TAG=0.1.2
            docker build -t devatherock/email-sender:$TAG docker
            docker tag devatherock/email-sender:$TAG registry.heroku.com/smtp-email-sender-api/web
            docker tag devatherock/email-sender:$TAG devatherock/email-sender:latest
            heroku container:login
            docker push registry.heroku.com/smtp-email-sender-api/web
            heroku container:release -a smtp-email-sender-api web
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push devatherock/email-sender:$TAG
            docker push devatherock/email-sender:latest

  notify_success:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
    steps:
      - run: /bin/simpleslack -c "#33ad7f" || true
  notify_failure:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Failure: {{.CircleBuildUrl}} by {{.CircleUsername}}"
    steps:
      - run:
          name: Failure notification
          command: /bin/simpleslack -c "#a1040c" || true
          when: on_fail

workflows:
  version: 2.1
  build_publish:
    jobs:
      - gradle/run:
          executor: jdk-executor
          context:
            - docker-credentials
          filters:
            branches:
              only: master
          post-steps:
            - run: cp build/libs/email-sender-*.jar docker/
            - persist_to_workspace:
                root: ~/email-sender
                paths:
                  - docker
      - publish:
          context:
            - docker-credentials
            - heroku-credentials
          requires:
            - gradle/run
      - notify_success:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - publish
      - notify_failure:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - publish
  pr_check:
    jobs:
      - gradle/run:
          executor: jdk-executor
          context:
            - docker-credentials
          filters:
            branches:
              ignore: master