slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.7.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

work_directory: &work_directory
  working_directory: ~/email-sender

resource_class: &resource_class
  resource_class: small
  
executors:
  jdk-executor:
    docker:
      - image: cimg/openjdk:17.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory
    
release_filter: &release_filter
  filters:
    branches:
      only: non-existent-branch
    tags:
      only: /^v[0-9\.]+$/
     
pr_filter: &pr_filter
  filters:
    branches:
      ignore: master

version: 2.1
jobs:
  changelog_updater:
    docker:
    - image: devatherock/changelog-updater:latest
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    <<: *resource_class
    environment:
      VELA_BUILD_AUTHOR: "renovate[bot]"
      VELA_BUILD_AUTHOR_EMAIL: "29139614+renovate[bot]@users.noreply.github.com"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4a:86:fe:0e:c3:0e:ad:0d:1d:5c:3e:48:cf:28:39:5d"
      - checkout
      - run: sh /scripts/entry-point.sh
      
  validate_yamls:
    docker:
      - image: devatherock/drone-yaml-validator:2.1.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - run: sh /scripts/entry-point.sh

  test:
    executor: jdk-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/email-sender
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies
      - run: |
          ./gradlew check
      - store_test_results:
          path: build/test-results

  build:
    executor: jdk-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/email-sender
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies
      - run: |
          ./gradlew build
          cp build/libs/email-sender-*.jar docker/
      - persist_to_workspace:
          root: ~/email-sender
          paths:
            - build
            - docker
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results

  publish:
    executor: jdk-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/email-sender
      - run:
          name: Build and push the docker image
          command: |
            TAG=${CIRCLE_SHA1:0:8}
            docker build -t devatherock/email-sender:$TAG docker
            docker tag devatherock/email-sender:$TAG devatherock/email-sender:latest
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push devatherock/email-sender:$TAG
            docker push devatherock/email-sender:latest
            
  dockerhub_readme:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - run: |
          docker run -v $PWD:/workspace \
              -e DOCKERHUB_USERNAME \
              -e DOCKERHUB_PASSWORD \
              -e DOCKERHUB_REPOSITORY='devatherock/email-sender' \
              -e SHORT_DESCRIPTION='REST API to send emails' \
              -e README_FILEPATH='/workspace/README.md' \
              peterevans/dockerhub-description:3.4.1
            
  integration_test:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - attach_workspace:
          at: ~/email-sender
      - run: |
          make integration-test
      - store_test_results:
          path: build/test-results

  publish_release:
    executor: jdk-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/email-sender
      - run: |
          TAG=${CIRCLE_TAG#v}
          DEV_TAG=${CIRCLE_SHA1:0:8}
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker pull devatherock/email-sender:$DEV_TAG
          docker tag devatherock/email-sender:$DEV_TAG devatherock/email-sender:$TAG
          docker push devatherock/email-sender:$TAG

  deploy:
    executor: jdk-executor
    steps:
      - run:
          name: Trigger deployment to render.com
          command: |
            curl $RENDER_DEPLOY_HOOK

  notify:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack -c "#33ad7f" || true

workflows:
  version: 2.1
  build_publish:
    jobs:
      - validate_yamls:
          context:
            - docker-credentials
          filters:
            branches:
              only: master
      - build:
          context:
            - docker-credentials
          requires:
            - validate_yamls
      - publish:
          context:
            - docker-credentials
          requires:
            - build
      - dockerhub_readme:
          context:
            - docker-credentials
            - dockerhub-readme-credentials
          requires:
            - publish
      - integration_test:
          context:
            - docker-credentials
          requires:
            - dockerhub_readme
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - integration_test
            
  release:
    jobs:
      - publish_release:
          context:
            - docker-credentials
          <<: *release_filter
      - deploy:
          context:
            - docker-credentials
          <<: *release_filter
          requires:
            - publish_release
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          <<: *release_filter
          requires:
            - deploy
            
  pr_check:
    jobs:
      - changelog_updater:
          context:
            - docker-credentials
            - changelog-updater-credentials
          <<: *pr_filter
      - validate_yamls:
          context:
            - docker-credentials
          requires:
            - changelog_updater
      - test:
          context:
            - docker-credentials
          <<: *pr_filter
          requires:
            - validate_yamls